name: Convert YAML Rulesets to MRS

on:
  push:
    paths:
      - "rules/*.yaml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: git pull

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl wget git jq

      - name: Download and install Mihomo
        run: |
          curl -L https://github.com/MetaCubeX/mihomo/releases/download/v1.19.9/mihomo-linux-amd64-v1.19.9.deb -o mihomo.deb
          sudo apt install --fix-missing ./mihomo.deb

      - name: Convert all YAML → MRS
        run: |
          mkdir -p mrs
          for f in rules/*.yaml; do
            name=$(basename "$f" .yaml)
            mihomo convert-ruleset domain yaml "rules/$name.yaml" "mrs/$name.mrs"
            echo "✅ Converted $name.yaml → $name.mrs"
          done

      - name: Commit and push MRS files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mrs/*.mrs || true
          git commit -m "Auto-generate MRS files" || echo "No changes"
          git push
