name: Convert YAML Rulesets to MRS

on:
  push:
    paths:
      - "rules/*.yaml"
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert YAML → MRS
        run: |
          docker run --rm -v ${{ github.workspace }}:/data metacubex/mihomo \
            sh -c '
            for f in /data/rules/*.yaml; do
              name=$(basename "$f" .yaml)
              /mihomo convert-ruleset domain yaml "/data/rules/$name.yaml" "/data/rules/$name.mrs"
              echo "✅ Converted $name.yaml → $name.mrs"
            done
            '

      - name: Commit and push MRS files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rules/*.mrs || true
          git commit -m "Auto-generate MRS files" || echo "No changes"
          git push
